// Placeholder shown in location pickers before a user has picked a city —
// treated as "no location filter" everywhere it's read back.
export const NO_LOCATION_LABEL = "Add Location";

// Major Pakistani cities mapped to their GPO postal code, used to auto-fill
// the postal code once a user picks their city during registration.
export const PAKISTAN_CITIES = [
  { name: "Abbottabad", postalCode: "22010" },
  { name: "Ahmedpur East", postalCode: "63350" },
  { name: "Alipur", postalCode: "34090" },
  { name: "Attock", postalCode: "43600" },
  { name: "Bahawalnagar", postalCode: "62300" },
  { name: "Bahawalpur", postalCode: "63100" },
  { name: "Bhalwal", postalCode: "40400" },
  { name: "Burewala", postalCode: "61010" },
  { name: "Chakwal", postalCode: "48800" },
  { name: "Chaman", postalCode: "87950" },
  { name: "Chichawatni", postalCode: "57200" },
  { name: "Chiniot", postalCode: "35400" },
  { name: "Chishtian", postalCode: "62800" },
  { name: "Dadu", postalCode: "76300" },
  { name: "Daska", postalCode: "51010" },
  { name: "Depalpur", postalCode: "55110" },
  { name: "Dera Ghazi Khan", postalCode: "32200" },
  { name: "Dera Ismail Khan", postalCode: "29050" },
  { name: "Faisalabad", postalCode: "38000" },
  { name: "Faqirwali", postalCode: "62700" },
  { name: "Ferozwala", postalCode: "39350" },
  { name: "Gilgit", postalCode: "15100" },
  { name: "Ghotki", postalCode: "65550" },
  { name: "Gojra", postalCode: "36000" },
  { name: "Gujranwala", postalCode: "52250" },
  { name: "Gujrat", postalCode: "50700" },
  { name: "Hafizabad", postalCode: "52100" },
  { name: "Hasilpur", postalCode: "63400" },
  { name: "Hyderabad", postalCode: "71000" },
  { name: "Islamabad", postalCode: "44000" },
  { name: "Jacobabad", postalCode: "79000" },
  { name: "Jampur", postalCode: "32360" },
  { name: "Jaranwala", postalCode: "37500" },
  { name: "Jhang", postalCode: "35200" },
  { name: "Jhelum", postalCode: "49600" },
  { name: "Kabirwala", postalCode: "60800" },
  { name: "Kamalia", postalCode: "36300" },
  { name: "Kamoke", postalCode: "52470" },
  { name: "Kandhkot", postalCode: "79800" },
  { name: "Karachi", postalCode: "74200" },
  { name: "Kasur", postalCode: "55050" },
  { name: "Khairpur", postalCode: "66020" },
  { name: "Khanewal", postalCode: "58150" },
  { name: "Khanpur", postalCode: "64100" },
  { name: "Kohat", postalCode: "26000" },
  { name: "Kot Addu", postalCode: "34220" },
  { name: "Kunri", postalCode: "69300" },
  { name: "Larkana", postalCode: "77150" },
  { name: "Lahore", postalCode: "54000" },
  { name: "Layyah", postalCode: "31200" },
  { name: "Mandi Bahauddin", postalCode: "50400" },
  { name: "Mardan", postalCode: "23200" },
  { name: "Mianwali", postalCode: "42200" },
  { name: "Mingora (Swat)", postalCode: "19130" },
  { name: "Mirpur (AJK)", postalCode: "10250" },
  { name: "Mirpur Khas", postalCode: "69000" },
  { name: "Multan", postalCode: "60000" },
  { name: "Muridke", postalCode: "39100" },
  { name: "Muzaffarabad (AJK)", postalCode: "13100" },
  { name: "Muzaffargarh", postalCode: "34200" },
  { name: "Nawabshah (Shaheed Benazirabad)", postalCode: "67450" },
  { name: "Naushahro Feroze", postalCode: "67480" },
  { name: "Nowshera", postalCode: "24100" },
  { name: "Okara", postalCode: "56300" },
  { name: "Pakpattan", postalCode: "57400" },
  { name: "Pattoki", postalCode: "55210" },
  { name: "Peshawar", postalCode: "25000" },
  { name: "Quetta", postalCode: "87300" },
  { name: "Rahim Yar Khan", postalCode: "64200" },
  { name: "Rawalpindi", postalCode: "46000" },
  { name: "Sadiqabad", postalCode: "68400" },
  { name: "Sahiwal", postalCode: "57000" },
  { name: "Sambrial", postalCode: "51060" },
  { name: "Sargodha", postalCode: "40100" },
  { name: "Sheikhupura", postalCode: "39350" },
  { name: "Shikarpur", postalCode: "78100" },
  { name: "Sialkot", postalCode: "51310" },
  { name: "Skardu", postalCode: "16100" },
  { name: "Sukkur", postalCode: "65200" },
  { name: "Tando Allahyar", postalCode: "70010" },
  { name: "Tando Adam", postalCode: "70400" },
  { name: "Tando Muhammad Khan", postalCode: "70600" },
  { name: "Toba Tek Singh", postalCode: "36050" },
  { name: "Turbat", postalCode: "92600" },
  { name: "Umerkot", postalCode: "69100" },
  { name: "Vehari", postalCode: "61100" },
  { name: "Wah Cantonment", postalCode: "47040" },
  { name: "Wazirabad", postalCode: "52000" },
  { name: "Zhob", postalCode: "85200" },
].sort((a, b) => a.name.localeCompare(b.name));

export function getPostalCodeForCity(cityName) {
  const match = PAKISTAN_CITIES.find((city) => city.name === cityName);
  return match ? match.postalCode : "";
}
